name: Build & Release eagle plugin CI/CD Pipeline

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  reset-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - run: gh release delete nightly --cleanup-tag -y -R ${{ github.repository }}

      - run: gh release create nightly --latest -t "Nightly Release" -R ${{ github.repository }}

  build-and-upload-release:
    needs: reset-release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Generate compressed package
        run: cd ./dist && zip -r stable-diffusion-png-extractor.eagleplugin * && cd ..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stable-diffusion-png-extractor-${{ github.sha }}
          path: ./dist/stable-diffusion-png-extractor.eagleplugin

      - name: Release eagle plugin
        run: gh release upload nightly ./dist/stable-diffusion-png-extractor.eagleplugin -R ${{ github.repository }}
